os: windows
language: go
go:
  - 1.11.x
before_install:
  - echo before_install
  - wget https://github.com/go-task/task/releases/download/v2.3.0/task_windows_amd64.zip
  - dir
install:
  - echo install
before_script:
  - echo before_script
script:
  - echo script
after_success:
  - echo after_success
after_failure:
  - echo after_failure
after_script:
  - echo after_script